version: '3'
services:
#  ollama:
#    image: ollama/ollama:0.6.6
#    volumes:
#      - ./ollama:/root/.ollama
#    ports:
#      - "11434:11434"

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'