spring:
  application:
    name: kyc

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

    mcp:
      client:
        stdio:
          connections:
            brave-search:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}


logging.level.org.springframework.ai: DEBUG