spring:
  application:
    name: kyc

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct
    #      api-key: ${OPENAI_API_KEY}

    mcp:
      client:
        stdio:
          connections:
            brave-search:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}


logging.level.org.springframework.ai: DEBUG