spring:
  application:
    name: kyc

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: compound-beta

logging.level.org.springframework.ai: DEBUG